# Generated by Django 5.0.7 on 2026-09-11 05:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TruckLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('zone', models.CharField(blank=True, max_length=20)),
                ('trading_from', models.TimeField(default=datetime.time(11, 0))),
                ('trading_until', models.TimeField(default=datetime.time(22, 0))),
                ('is_live', models.BooleanField(default=True)),
                ('next_return', models.DateTimeField(blank=True, null=True)),
                ('ready_minutes', models.PositiveSmallIntegerField(default=15)),
                ('slot_capacity', models.PositiveSmallIntegerField(default=8)),
            ],
            options={
                'verbose_name': 'truck location',
            },
        ),
    ]
