# Generated by Django 5.0.7 on 2026-09-10 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sauce',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, unique=True)),
                ('slug', models.SlugField(unique=True)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('is_available', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.AddField(
            model_name='menuitem',
            name='is_spicy',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='prep_minutes',
            field=models.PositiveSmallIntegerField(default=15),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='sauces',
            field=models.ManyToManyField(blank=True, related_name='items', to='menu.sauce'),
        ),
    ]
