# Generated by Django 5.0.7 on 2026-09-17 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0004_review_is_hidden'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='static_image',
            field=models.CharField(blank=True, max_length=80),
        ),
    ]
