# Generated by Django 5.0.7 on 2026-09-10 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='note',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='sauce_snapshot',
            field=models.CharField(blank=True, max_length=40),
        ),
    ]
